# Generated by Django 3.1.4 on 2021-01-23 22:00

from django.db import migrations, models
import django.db.models.deletion
import gshs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infogigi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('maker', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, choices=[('흑백', '흑백'), ('컬러', '컬러')], max_length=6, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'infogigi',
                'ordering': ['buy_date'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='성명')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='핸드폰')),
                ('tel_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='내선')),
                ('status', models.BooleanField(default=True, verbose_name='재직')),
                ('bigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='비고')),
            ],
            options={
                'db_table': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(blank=True, default=0, max_length=50)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'place',
                'ordering': ['building'],
            },
        ),
        migrations.CreateModel(
            name='Productgubun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gubun_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productgubun',
            },
        ),
        migrations.CreateModel(
            name='Softwarestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('_remaining', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'softwarestock',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('damdang_name', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('bigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vendor',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Softwarerental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('people', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.people')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place')),
                ('softwarestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gshs.softwarestock')),
            ],
            options={
                'db_table': 'softwarerental',
                'ordering': ['-rental_date'],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('cause', models.CharField(max_length=200)),
                ('result', models.TextField()),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('infogigi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.infogigi')),
            ],
            options={
                'db_table': 'repair',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Productbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('maker', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(max_length=100)),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('productgubun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.productgubun')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.vendor')),
            ],
            options={
                'db_table': 'productbuy',
                'ordering': ['productgubun'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', validators=[gshs.models.file_size])),
                ('suri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.repair')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place', verbose_name='부서명'),
        ),
        migrations.CreateModel(
            name='Jaego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('rental_status', models.CharField(blank=True, choices=[('yes', '가능'), ('no', '대여중')], default='yes', max_length=3)),
                ('not_use', models.BooleanField(default=False)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('infogigi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.infogigi')),
            ],
            options={
                'db_table': 'jaego',
                'ordering': ['-rental_status'],
            },
        ),
        migrations.AddField(
            model_name='infogigi',
            name='people',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.people'),
        ),
        migrations.AddField(
            model_name='infogigi',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place'),
        ),
        migrations.AddField(
            model_name='infogigi',
            name='productgubun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.productgubun'),
        ),
        migrations.CreateModel(
            name='Gigirental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('jaego', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.jaego')),
                ('people', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.people')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place')),
            ],
            options={
                'db_table': 'gigirental',
                'ordering': ['-rental_date'],
            },
        ),
        migrations.CreateModel(
            name='Bupumchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('change_cause', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('infogigi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.infogigi')),
                ('productbuy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.productbuy')),
            ],
            options={
                'db_table': 'bupumchange',
                'ordering': ['-created_date'],
            },
        ),
    ]
