# Generated by Django 3.1.4 on 2021-01-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarestock',
            old_name='_remaining',
            new_name='remaining',
        ),
    ]
