# Generated by Django 3.1.4 on 2021-01-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gigirental',
        ),
    ]
