# Generated by Django 3.1.4 on 2021-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarestock',
            name='license',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='softwarestock',
            name='maker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jaego',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('yes', '대여가능'), ('no', '대여중')], default='yes', max_length=3),
        ),
    ]
