# Generated by Django 3.1.4 on 2021-01-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0002_delete_gigirental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigirental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now=True, null=True)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('jaego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.jaego')),
                ('people', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.people')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place')),
            ],
            options={
                'db_table': 'gigirental',
                'ordering': ['-rental_date'],
            },
        ),
    ]
