# Generated by Django 3.1.4 on 2021-01-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0002_auto_20210123_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarestock',
            old_name='remaining',
            new_name='remain',
        ),
    ]
