# Generated by Django 3.1.4 on 2021-01-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0003_auto_20210123_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarerental',
            name='softwarestock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.softwarestock'),
        ),
        migrations.AlterField(
            model_name='softwarestock',
            name='remain',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
