# Generated by Django 3.1.4 on 2021-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0004_auto_20210124_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarerental',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='남은 수량 보다 많게 대여할 수 없습니다.'),
        ),
    ]
