# Generated by Django 3.1.4 on 2021-01-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0005_auto_20210121_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigirental',
            name='due_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
