# Generated by Django 3.1.4 on 2021-01-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0007_auto_20210121_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigirental',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
