# Generated by Django 3.1.4 on 2021-01-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0005_auto_20210124_2002'),
        ('gshs', '0008_auto_20210121_2124'),
    ]

    operations = [
    ]
