# Generated by Django 3.1.4 on 2021-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0011_auto_20210126_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarerental',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='남은 수량 보다 많이 입력하지마세요.!'),
        ),
    ]
