# Generated by Django 3.1.4 on 2021-01-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0012_auto_20210126_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bupumchange',
            name='change_cause',
        ),
    ]
