# Generated by Django 3.1.4 on 2021-01-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0013_remove_bupumchange_change_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bupumchange',
            name='productbuy',
            field=models.ForeignKey(limit_choices_to={'productgubun': 'CONSUMABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.productbuy'),
        ),
    ]
