# Generated by Django 3.1.4 on 2021-01-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0014_auto_20210126_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bupumchange',
            name='productbuy',
            field=models.ForeignKey(limit_choices_to={'productgubun': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.productbuy'),
        ),
    ]
