# Generated by Django 3.1.4 on 2021-01-27 21:01

from django.db import migrations, models
import gshs.models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0015_auto_20210126_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m', validators=[gshs.models.file_size]),
        ),
    ]
