# Generated by Django 3.1.4 on 2021-02-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0016_auto_20210127_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infogigi',
            options={'ordering': ['productgubun', 'buy_date']},
        ),
        migrations.AlterModelOptions(
            name='productbuy',
            options={'ordering': ['productgubun', 'model']},
        ),
        migrations.AlterField(
            model_name='bupumchange',
            name='infogigi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.infogigi'),
        ),
    ]
