# Generated by Django 3.1.6 on 2021-02-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0017_auto_20210202_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gshs.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='buseo',
            field=models.BooleanField(default=True),
        ),
    ]
