# Generated by Django 3.1.6 on 2021-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0018_auto_20210209_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgubun',
            name='table_name',
            field=models.CharField(default='infogigi', max_length=30),
        ),
    ]
