# Generated by Django 3.1.4 on 2021-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0021_auto_20210215_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='buseo',
            field=models.CharField(choices=[('부서', '부서'), ('강의실', '강의실'), ('강당', '강당'), ('실험실', '실험실'), ('기타', '기타')], default=1, max_length=30),
        ),
    ]
