# Generated by Django 3.1.4 on 2021-02-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0023_auto_20210215_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='place',
        ),
        migrations.AlterField(
            model_name='bupumchange',
            name='productbuy',
            field=models.ForeignKey(limit_choices_to={'productgubun': 'cunsumables'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.productbuy'),
        ),
    ]
