# Generated by Django 3.1.4 on 2021-02-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0024_auto_20210216_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bupumchange',
            name='productbuy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.productbuy'),
        ),
    ]
