# Generated by Django 3.1.4 on 2021-02-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshs', '0025_auto_20210216_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.place'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='infogigi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gshs.infogigi'),
        ),
    ]
