# Generated by Django 3.1.4 on 2021-02-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
