# Generated by Django 3.1.4 on 2021-02-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20210205_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
