# Generated by Django 3.1.4 on 2021-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20210205_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='content',
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
